project_name: urch

builds:
  - env:
    - CGO_ENABLED=0
    ldflags:
      - -w -s
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64]
    goarm:
      - "7"
      - "6"

dockers:

  - image_templates:
      - "soulteary/ubuntu-remote-control-helper:linux-amd64-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-amd64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-v2"

  - image_templates:
      - "soulteary/ubuntu-remote-control-helper:linux-arm64-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-arm64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-v2"

  - image_templates:
      - "soulteary/ubuntu-remote-control-helper:linux-armv7-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-armv7"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-v2"

  - image_templates:
      - "soulteary/ubuntu-remote-control-helper:linux-armv6-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-armv6"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/ubuntu-remote-control-helper"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-v2"


docker_manifests:
  - name_template: "soulteary/ubuntu-remote-control-helper:{{ .Tag }}"
    image_templates:
      - "soulteary/ubuntu-remote-control-helper:linux-amd64-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-arm64-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-armv7-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-armv6-{{ .Tag }}"
    skip_push: "false"

  - name_template: "soulteary/ubuntu-remote-control-helper:latest"
    image_templates:
      - "soulteary/ubuntu-remote-control-helper:linux-amd64-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-arm64-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-armv7-{{ .Tag }}"
      - "soulteary/ubuntu-remote-control-helper:linux-armv6-{{ .Tag }}"
    skip_push: "false"